import './Home.css';

function Home() {
    return (
        <div class="container mt-4">        
            <div className='row'>
                <div className='col'>
                    <div  style={{margin: "0",  padding: "0", color:'#4e4e4e' }}>
                        <h1>Tienda Online de Nutrición Deportiva, Dietética Natural y Accesorios</h1>
                        <p>¿Eres deportista y sabes que la mejor versión de ti mismo está aún por llegar? ¿Llevas o quieres seguir un estilo de vida saludable? Prepárate porque vas a ser&nbsp;<strong>uno de los miles de clientes HSN.&nbsp;</strong><strong>Comprobarás cómo la distancia que te separa de tus objetivos se acorta.</strong></p>
                        <p>Somos la tienda online de Nutrición Deportiva y Dietética Natural líder. Para nosotros tú eres el centro de todo. En HSN vas a encontrar un equipo con el que vas a identificarte, pues nuestro esfuerzo por cruzar la delgada línea entre lo notable y lo sobresaliente no entiende de límites.</p>
                        <h2>¿Quiénes somos y qué podemos aportarte?</h2>
                        <p>Impulsados por la experiencia de más de una década a tu servicio, caracterizada por la constante búsqueda de la excelencia, te presentamos <strong>la mejor selección de productos de nutrición deportiva y alimentación saludable del mercado</strong>, con independencia de cuál sea tu disciplina deportiva u objetivo.</p>
                        <p>Solo podemos invitarte a que compruebes las increíbles virtudes de todos nuestros productos: eficacia, sabor y textura de las fórmulas de nuestras proteínas (con Whey Protein a la cabeza) creatinas, aminoácidos de altura (como BCAA’s), productos BIO... <strong>¡Y todo lo que tenga que ver con el interés incesante por el cuidado de la salud!</strong></p>
                        <p>¿Cuál es nuestro objetivo? Llevar la Marca HSN a lo más alto y<strong>&nbsp;ofrecerte la mayor variedad de Nutrición Deportiva y Dietética Natural</strong> y, por último, pero no por eso menos importante, los mejores precios.</p>
                        <p>En HSN diseñamos, creamos y seleccionamos los mejores suplementos y alimentos naturales con los que puedes conseguir tus objetivos deportivos y ayudarte a llevar una vida más saludable.</p>
                        <p><strong>¡Únete a HSN para una alianza legendaria en el sector del fit-food!</strong></p>
                        <h2>Desarrollo y fabricación propia</h2>
                        <p>Desde nuestros comienzos en 2008, tu apoyo y nuestra labor incansable ha dado lugar a la creación de nuestras propias marcas de productos, bajo el nombre de HSN.&nbsp;&nbsp;</p>
                        <p>¿Sabes cuál es la base de todos nuestros productos? Fácil: estar fabricados en nuestras propias instalaciones bajo las mejores condiciones de control y con la calidad de las mejores materias primas e ingredientes.</p>
                        <p>En esta selección destacan nuestras creaciones “estrella”, aquellas que aúnan un amplio elenco de referencias de <strong>suplementos deportivos imbatibles</strong> que van a convertirse en piedra angular de tu rendimiento físico:</p>
                        <ul>
                            <li><i className="fa-solid fa-check" style={{ color: "#00b22d", marginRight: "5px" }}></i><a title="Comprar Productos SportSeries" href="https://www.hsnstore.com/marcas/sport-series">SportSeries</a>: selección de productos bajo formulaciones excepcionales que llegan de la mano de los mejores especialistas y con el respaldo de estudios científicos, elaborándose con las materias primas más selectas del mercado.</li>
                            <li><i className="fa-solid fa-check" style={{ color: "#00b22d", marginRight: "5px" }}></i><a title="Comprar Productos EssentialSeries" href="https://www.hsnstore.com/marcas/essential-series">EssentialSeries</a>: destinados a aquellas personas que han hecho de una existencia saludable su filosofía de vida, engloba complementos nutricionales que te permitirán mantener un óptimo estado de salud en coherencia con tus convicciones.</li>
                            <li><i className="fa-solid fa-check" style={{ color: "#00b22d", marginRight: "5px" }}></i><a title="Comprar Productos RawSeries" href="https://www.hsnstore.com/marcas/raw-series">RawSeries</a>: reflejo de nuestro sentido práctico, la componen productos “simples”, mayoritariamente de un único ingrediente, que sugieren hacer tus propias combinaciones, acordes a tus metas.</li>
                            <li><i className="fa-solid fa-check" style={{ color: "#00b22d", marginRight: "5px" }}></i><a title="Comprar Productos FlavourSeries" href="https://www.hsnstore.com/marcas/flavour-series">FlavourSeries</a>: ¿Quieres darle un sabor personal o diferente cada día a tus proteínas o bebidas deportivas? Elige entre la amplia gama de sabores de la línea FlavourSeries y añádelo a tus productos Raw o neutro (de proteínas, proteínas vegetales o bebidas deportivas y aminoácidos) para llenar de sabores distintos a tus complementos. ¡Añádele sabor a tus propias mezclas!</li>
                            <li><i className="fa-solid fa-check" style={{ color: "#00b22d", marginRight: "5px" }}></i><a title="Comprar Productos FoodSeries" href="https://www.hsnstore.com/marcas/food-series">FoodSeries</a>: destinada a compilar una amplia gama de alimentos saludables, la elevada calidad de sus materias primas se une a unos sabores increíbles, en una fusión inigualable.</li>
                            <li><i className="fa-solid fa-check" style={{ color: "#00b22d", marginRight: "5px" }}></i><a title="Comprar Productos BioSeries" href="https://www.hsnstore.com/marcas/bio-series">BioSeries</a>: productos orgánicos y alimentos bio, especial para quienes presentan una marcada inclinación por los suplementos naturales y ecológicos.</li>
                            <li><i className="fa-solid fa-check" style={{ color: "#00b22d", marginRight: "5px" }}></i><a title="Comprar Productos KetoSeries" href="https://www.hsnstore.com/marcas/keto-series">KetoSeries</a>: La revolución del mercado de la alimentación Keto. Deportistas, estudiantes, personas que hacen dietas cetogénicas... Esta línea es para vosotros. Fórmulas exclusivas de HSN: bajas en carbohidratos, con compuestos específicos nunca antes vistos en el mercado europeo.</li>
                            <li><i className="fa-solid fa-check" style={{ color: "#00b22d", marginRight: "5px" }}></i><a title="HSNaccesories" href="https://www.hsnstore.com/marcas/hsn-accessories" target="_blank" rel="noopener">HSNaccessories</a>: No solo fabricamos complementos para ayudarte a sacar lo mejor de tu rendimiento, sino que también te ofrecemos los mejores complementos (shakers, botellas, textil, etc). ¡Atrévete a llevarnos a todos lados!</li>
                            <li><i className="fa-solid fa-check" style={{ color: "#00b22d", marginRight: "5px" }}></i><a title="HSNpacks" href="https://www.hsnstore.com/marcas/hsn-packs" target="_blank" rel="noopener">HSNpacks</a>: ¿Buscas un objetivo concreto y quieres alcanzar los resultados? Déjate asesorar por nuestros packs completos de productos para deportes, metas u objetivos. Además, ¡aprovéchate de los descuentos especiales de estos packs!&nbsp;&nbsp;</li>
                        </ul>
                        <br/>
                        <p>¿Es poco para ti? <strong>¡Súmale las marcas top mundiales en nutrición deportiva!</strong></p>
                        <p>Una de ellas es Now Foods, marca líder en complementos alimenticios destinados al bienestar y la salud de todos.</p>
                        <p>Otra marca reconocida que encontrarás en nuestra tienda online HSN es Swanson, fabricante que apuesta por los códigos de variedad, calidad y buenas prácticas de fabricación.</p>
                        <p><strong>Y, ¿a qué precio? ¡A uno invencible!</strong> ¿O es que todavía no te hemos contado que nos encanta dar la bienvenida a nuestros nuevos clientes con un <strong>cupón descuento</strong> que te servirá para <a title="Comprar Aminoácidos" href="https://www.hsnstore.com/nutricion-deportiva/aminoacidos">comprar aminoácidos</a>, <a title="Comprar Proteínas" href="https://www.hsnstore.com/nutricion-deportiva/proteinas">proteínas</a> o cualquier producto natural que tengas en mente?</p>
                        <p><strong>¡Suscríbete a la newsletter y lo recibirás!</strong> Y una sugerencia: a partir de ahora no pierdas de vista tu mail porque con esta suscripción vas a recibir un aluvión virtual de <strong>descuentos exclusivos</strong> en forma de súper promociones. Aviso a navegantes: ¡Enganchan!</p>
                        <p>¿Cuándo puedes tener en casa tu compra? Tienes suerte porque con nuestros envíos express estarás probando todos los productos de tu compra online, <strong>¡en 24 horas!&nbsp;</strong>En el caso de envíos estándar, tendrás tu pedido en casa en 24 - 48 horas.</p>
                        <h2>Una Nueva Era en Nutrición Deportiva</h2>
                        <p>¿Has comprobado ya todo nuestro amplio catálogo de productos HSN? ¡Atento!&nbsp;</p>
                        <p>Nuestros batidos de proteínas&nbsp;como <a title="Evowhey Protein" href="https://www.hsnstore.com/marcas/sport-series/evowhey-protein">Evowhey Protein</a>&nbsp;causan furor (Proteína de Suero de Leche), si bien&nbsp;<a title="Hidrolizado de Proteína de Carne Evobeef" href="https://www.hsnstore.com/marcas/sport-series/evobeef-hidrolizado-de-carne-2-0-leucina-extra">Evobeef</a> (Proteína hidrolizada de carne) o la siempre alternativa&nbsp;<a title="Proteína de Soja Aislada EssentialSeries" href="https://www.hsnstore.com/marcas/essential-series/proteina-de-soja-aislada-2-0">Proteína Vegetal de Soja</a>, son otros de nuestros <strong>top ventas</strong>.&nbsp;Les siguen de cerca <strong>quemagrasas</strong> y <a title="Suplementos termogénicos" href="https://www.hsnstore.com/nutricion-deportiva/controlar-peso/termogenicos">termogénicos</a><strong>&nbsp;</strong>para <strong>perder peso</strong> con o sin estimulantes, que encuentran sus <em>máximos exponentes en</em>&nbsp;<a title="Comprar Quemagrasa Evobrun" href="https://www.hsnstore.com/marcas/sport-series/evoburn">Evoburn</a>, <a title="Comprar Cafeína en cápsulas" href="https://www.hsnstore.com/marcas/essential-series/cafeina-natural-200mg">cafeína natural en cápsulas</a>,&nbsp;<a title="Extracto de guaraná" href="https://www.hsnstore.com/marcas/essential-series/extracto-de-guarana-6-1-400mg">extracto de guaraná</a> o la <em>"celebritie"</em> del gym, la <a title="Comprar Carnitina" href="https://www.hsnstore.com/marcas/sport-series/evo-l-carnitina-3000">carnitina</a>, en plena escalada de puestos.</p>
                        <p><strong>¿Buscas complementar tu </strong><a title="Suplementos para Veganos" href="https://www.hsnstore.com/especialidades/apto-para-veganos">dieta vegana</a> <strong>o</strong> <a title="Suplementos para Vegetarianos" href="https://www.hsnstore.com/especialidades/apto-para-vegetarianos">nutrición vegetariana</a><strong>?</strong> Te ayudamos. En HSN no tenemos rival. Todo está perfectamente ordenado para que con un solo clic encargues <strong>24/7</strong> los mejores suplementos dietéticos para <a title="Suplementos para las articulaciones" href="https://www.hsnstore.com/salud-bienestar/huesos-y-articulaciones">cuidar tus articulaciones</a>, <a title="Suplementos para disminuir el colesterol" href="https://www.hsnstore.com/salud-bienestar/contra-colesterol">disminuir el colesterol</a>, <a title="Suplementos para dormir bien" href="https://www.hsnstore.com/salud-bienestar/estres-ansiedad">conciliar un sueño reparador</a> o potenciar tu sexualidad gracias al <a title="Alimentos para aumentar tu testosterona" href="https://www.hsnstore.com/blog/suplementos/sexualidad/top-10-alimentos-para-aumentar-testosterona/">aumento de testosterona</a> o libido.</p>
                        <p>No en vano, lo venimos anunciando hace tiempo: <strong><em>We are Nutrition!</em></strong></p>
                        <p><strong>¿Piensas en verde?</strong> ¡Nosotros también! Ya tenemos otro punto en común. Como firmes defensores de una <strong>nutrición sostenible en armonía con la protección de los recursos naturales</strong>, nos afanamos en lograr el bienestar animal. En esa línea, algunos de nuestros productos hablan por sí solos, como la proteína de suero de <a title="Leche procedente de vacas alimentadas con pasto" href="https://www.hsnstore.com/especialidades/alimentado-con-pasto">vacas alimentadas con pasto</a> o la <a title="Comprar Evoegg" href="https://www.hsnstore.com/marcas/sport-series/evoegg-2-0-albumina-de-huevo">proteína de huevos de gallinas sueltas</a>. BioSeries es la viva imagen del respeto al medio ambiente que deseamos transmitir.&nbsp;</p>
                        <h2>Completa tu compra con los mejores accesorios</h2>
                        <p>El ser líderes en Nutrición Deportiva y Dietética Natural nos hace disponer de los mejores productos online. Súmate a la tendencia de los <a title="Suplementos Pre-Entreno" href="https://www.hsnstore.com/nutricion-deportiva/pre-entrenamiento">pre-entrenamientos</a> como <a title="Comprar Arginina" href="https://www.hsnstore.com/ingredientes/arginina">Arginina</a> o <a title="Comprar Beta-Alanina" href="https://www.hsnstore.com/ingredientes/beta-alanina">Beta-Alanina</a>, <strong>geles energéticos</strong>, <a title="Comprar Barritas de Proteínas" href="https://www.hsnstore.com/nutricion-deportiva/barritas/proteinas">barritas de proteínas</a> como <a title="Barritas de Proteínas Evobars" href="https://www.hsnstore.com/marcas/sport-series/evobars-protein-bars">Evobars</a>, recuperadores con <a title="Comprar Electrolitos" href="https://www.hsnstore.com/marcas/sport-series/evolytes-en-polvo">electrolitos</a> y <strong>aminoácidos</strong>. Aunque quizás lo tuyo sean vitaminas y minerales en cápsulas vegetales <strong>para recuperar energía, vitalidad y fuerza tras el duro entreno</strong>.</p>
                        <p>Todo ello sin olvidar que una dieta y suplementación perfectas exigen la disponibilidad de productos <a title="Productos Sin Gluten" href="https://www.hsnstore.com/especialidades/sin-gluten">sin gluten</a> y <a title="Productos Sin Lactosa" href="https://www.hsnstore.com/especialidades/sin-lactosa">sin lactosa</a>. ¿Las grandes marcas te apasionan? Apuesta entonces por <a title="Marca de Vitaminas Vitaminalia" href="https://www.hsnstore.com/marcas/vitaminalia">Vitaminalia</a> o <strong>EssentialSeries</strong> y otras muchas en las que no faltarán suplementos de <a title="Omega 3" href="https://www.hsnstore.com/blog/nutricion/grasas/omega-3/">ácidos grasos omega 3</a>, <a title="Qué es el Magnesio" href="https://www.hsnstore.com/blog/nutricion/minerales/magnesio/">magnesio</a> o <a title="Todo sobre el Colágeno" href="https://www.hsnstore.com/blog/suplementos/salud-articular/colageno/">colágeno</a>, que cubran al cien por cien tus exigencias nutricionales.</p>
                        <p>Pero ten en cuenta que para cumplir tus objetivos no solo necesitarás la mejor dieta natural o contar con los mejores complementos, sino también poder contar con los mejores <a title="Accesorios Deportivos" href="https://www.hsnstore.com/accesorios-deportivos">accesorios para el entrenamiento</a>, <a title="Shakers y Botellas Deportivas" href="https://www.hsnstore.com/accesorios-deportivos/shakers-y-botellas-deportivas">botellas deportivas o shakers</a> para tus batidos de proteínas con los que personalizar tu outfit deportivo.</p>
                        <p>¿Cierras los ojos y solo ves suplementos? ¡Háztelo mirar! Igual tienes <a title="Falta de Vitamina D" href="https://www.hsnstore.com/blog/nutricion/vitaminas/d/falta-o-carencia/">falta de vitamina D</a> o <a title="Deficiencia de Vitamina B12" href="https://www.hsnstore.com/blog/nutricion/vitaminas/b12/falta/">deficiencia de vitamina B12</a> y necesitas <a title="Comprar Multivitamínicos" href="https://www.hsnstore.com/nutricion-deportiva/multivitaminicos">comprar multivitamínicos</a> para suplirla. Ningún problema ya que en HSNstore.com disponemos del más extenso catálogo en el que <a title="Comprar Vitaminas y Minerales" href="https://www.hsnstore.com/nutricion-deportiva/vitaminas">comprar vitaminas</a>&nbsp;al mejor precio. Elígelos en formatos <strong>cápsulas fáciles de tragar, polvo o líquido y ¡arriba ese ánimo!</strong></p>
                        <h2>Queremos ayudarte con todas tus consultas sobre Nutrición Deportiva y Suplementación</h2>
                        <p>En HSN somos conscientes de que en la confianza está la clave de una buena relación tienda-usuario. Por esa razón, más allá de ofrecerte productos de alta calidad al mejor precio, queremos hacerte llegar <strong>información que aporte valor, gratuita y objetiva</strong> para ayudarte a dar en el blanco de la diana en tu elección.</p>
                        <p>Estás tardando en ir al Blog HSN y echar un vistazo a <strong>artículos de entrenamiento, actividad física y un sinfín de complementos alimenticios</strong> con descripciones detalladas de cada uno de los <a title="Ingredientes Naturales" href="https://www.hsnstore.com/ingredientes">principales ingredientes naturales</a> que vas a encontrar en nuestros productos.</p>
                        <p>Un último apunte: parte de esa confianza se basa en poder consultar la garantía de calidad de nuestros productos.&nbsp;Y si aún así te has quedado con ganas de saber más sobre nosotros, ¡no dudes en navegar por nuestra tienda online!</p>
                        <p><em>Let’s go!</em> ¡Y No lo olvides, HSN es nutrición!</p>
                        <p><strong>We are Nutrition!</strong></p>
                        <p>&nbsp;</p>
                    </div>
                </div>
            </div>  
        </div>
    );
}
export default Home;